--- 
kind: pipeline
name: default
steps: 
  - 
    commands: 
      - "npm install"
      - "npm run lint"
    image: node
    name: test
  - 
    commands: 
      - "apk --no-cache add zip bash git"
      - "git config user.email \"automation@tosdr.org\""
      - "git config user.name \"ToS;DR Automation\""
      - "npm version $DRONE_DEPLOY_TO --no-git-tag-version"
      - "cat src/manifest.json | sed '/\"version\":/ s/\"version\":[^,]*/\"version\":\"'$(npm run env | grep npm_package_version | cut -d '=' -f 2)'\"/' > src/manifest.json"
      - "git add . && git commit -m \"Update manifest version\""
      - "git tag $(npm run env | grep npm_package_version | cut -d '=' -f 2) -a -m \"Updated to $(npm run env | grep npm_package_version | cut -d '=' -f 2)\""
      - "sed -i 's/\\r$//' build.sh"
    image: "node:alpine"
    name: "Up Version"
    when: 
      event: 
        - promote
  - 
    image: appleboy/drone-git-push
    name: "Push Tags"
    settings: 
      author_email: automation@tosdr.org
      author_name: "ToS;DR Automation"
      branch: master
      commit: true
      commit_message: Release
      followtags: true
      force: false
      remote: "git@github.com:tosdr/browser-extensions.git"
      ssh_key: 
        from_secret: SSH_KEY
    when: 
      event: 
        - promote
      target: 
        - patch
        - minor
        - major
  - 
    commands: 
      - "apk --no-cache add zip bash"
      - "bash build.sh"
    image: "node:alpine"
    name: "Build Extension"
  - 
    image: plugins/gpgsign
    name: "Sign Release"
    settings: 
      files: 
        - dist/*
      key: 
        from_secret: SIGN_KEY
      passphrase: 
        from_secret: SIGN_KEY_PASS
    when: 
      branch: 
        - master
      event: 
        - push
  - 
    image: plugins/s3
    name: "Upload Build Artifacts"
    settings: 
      access_key: 
        from_secret: aws_access_key_id
      bucket: tosdr-artifacts
      endpoint: "https://s3.eu-west-2.jbcdn.net"
      secret_key: 
        from_secret: aws_secret_access_key
      source: ./dist/*
      strip_prefix: true
      target: "/browser-extensions/builds/${DRONE_BUILD_NUMBER}"
    when: 
      branch: 
        - master
      event: 
        - push
  - 
    image: appleboy/drone-discord
    name: "Discord Build Notification"
    settings: 
      message: |
          {{#success build.status}}
          Browser Extension Build {{build.number}} succeeded. The artifacts can be downloaded here:
            
          Chrome:
          https://tosdr-artifacts.s3.eu-west-2.jbcdn.net/browser-extensions/builds/{{build.number}}/dist/chrome.zip
            
          Firefox:
          https://tosdr-artifacts.s3.eu-west-2.jbcdn.net/browser-extensions/builds/{{build.number}}/dist/firefox.xpi
            
          Build:
          {{build.link}}
          {{else}}
          Browser Extension Build {{build.number}} failed.
          
          Build:
          {{build.link}}
          {{/success}}
          ---
      webhook_id: 
        from_secret: WEBHOOK_ID
      webhook_token: 
        from_secret: WEBHOOK_SECRET
  - 
    image: plugins/github-release
    name: "Publish GitHub Release"
    settings: 
      api_key: 
        from_secret: RELEASE_TOKEN
      checksum: 
        - sha256
      files: 
        - dist/*
    when: 
      event: 
        - tag
  - 
    image: plugins/s3
    name: "Upload Release Artifacts"
    settings: 
      access_key: 
        from_secret: aws_access_key_id
      bucket: tosdr-artifacts
      endpoint: "https://s3.eu-west-2.jbcdn.net"
      secret_key: 
        from_secret: aws_secret_access_key
      source: ./dist/*
      target: "/browser-extensions/releases/${DRONE_TAG}"
    when: 
      event: 
        - tag
