kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: build_tag_minor
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - npm version minor
  - sed -i 's/\r$//' build.sh
  - bash build.sh
  when:
    event:
    - promote
    target:
    - production

- name: push tag
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:tosdr/browser-extensions.git
    force: false
    ssh_key:
        from_secret: SSH_KEY
    commit: true
    follow_tags: true
    commit_message: "[skip ci] Minor Release"
  when:
    event:
    - promote
    target:
    - production

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files:
    - dist/*
    checksum:
    - sha256
  when:
    event:
    - promote
    target:
    - production
node:
  os: linux