kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: build_tag_patch
  image: node:alpine
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - npm version patch -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - bash build.sh
  when:
    event:
    - promote
    target:
    - patch

- name: build_tag_minor
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - npm version minor -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - bash build.sh
  when:
    event:
    - promote
    target:
    - minor

- name: build_tag_major
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - npm version major -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - bash build.sh
  when:
    event:
    - promote
    target:
    - major

- name: push tag
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:tosdr/browser-extensions.git
    force: false
    ssh_key:
        from_secret: SSH_KEY
    commit: true
    author_name: "ToS;DR Automation"
    author_email: "automation@tosdr.org"
    followtags: true
    commit_message: "Release"
  when:
    event:
    - promote

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files:
    - dist/*
    checksum:
    - sha256
  when:
    event:
    - tag
node:
  os: linux