kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: Up Version As Patch
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - git add .
  - git commit -m "Upped package-lock.json"
  - git status
  - npm version patch -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - cat src/manifest.json | sed '/"version":/ s/"version":[^,]*/"version":"'$(npm run env | grep npm_package_version | cut -d '=' -f 2)'"/' > src/manifest.json
  when:
    event:
    - promote
    target:
    - patch

- name: Up Version As Minor
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - git add .
  - git commit -m "Upped package-lock.json"
  - git status
  - npm version minor -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - cat src/manifest.json | sed '/"version":/ s/"version":[^,]*/"version":"'$(npm run env | grep npm_package_version | cut -d '=' -f 2)'"/' > src/manifest.json
  when:
    event:
    - promote
    target:
    - minor

- name: Up Version As Major
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - git add .
  - git commit -m "Upped package-lock.json"
  - git status
  - npm version major -m "Upgrade to %s"
  - sed -i 's/\r$//' build.sh
  - cat src/manifest.json | sed '/"version":/ s/"version":[^,]*/"version":"'$(npm run env | grep npm_package_version | cut -d '=' -f 2)'"/' > src/manifest.json
  when:
    event:
    - promote
    target:
    - major

- name: Push Tags
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:tosdr/browser-extensions.git
    force: false
    ssh_key:
        from_secret: SSH_KEY
    commit: true
    author_name: "ToS;DR Automation"
    author_email: "automation@tosdr.org"
    followtags: true
    commit_message: "Release"
  when:
    event:
    - promote

- name: Build Extension
  image: node:alpine
  commands:
  - apk --no-cache add zip bash
  - bash build.sh
  when:
    event:
    - tag

- name: Publish Release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files:
    - dist/*
    checksum:
    - sha256
  when:
    event:
    - tag
node:
  os: linux